version: "{build}"

clone_folder: c:\go\src\github.com\avast\retry-go

#os: Windows Server 2012 R2
platform: x64

install:
  - go version
  - go env
  - go get -v -t

build_script:
  - go test -v ./...
